### ISSUE TITLE
Keep running into utf-8 errors in Python 3.x

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [qubole/qds-sdk-py#175]
`qds.py --token=$QUBOLE_KEY_AVAZQUEZ hivecmd getresult "37309793" > my_output`

Fails with:

```
Traceback (most recent call last):
  File "/Users/amelio/anaconda/envs/py35/bin/qds.py", line 604, in <module>
    sys.exit(main())
  File "/Users/amelio/anaconda/envs/py35/bin/qds.py", line 557, in main
    return cmdmain(a0, args)
  File "/Users/amelio/anaconda/envs/py35/bin/qds.py", line 195, in cmdmain
    return globals()[action + "action"](cmdclass, args)
  File "/Users/amelio/anaconda/envs/py35/bin/qds.py", line 161, in getresultaction
    return _getresult(cmdclass, cmd)
  File "/Users/amelio/anaconda/envs/py35/bin/qds.py", line 119, in _getresult
    cmd.get_results(sys.stdout, delim='\t')
  File "/Users/amelio/anaconda/envs/py35/lib/python3.5/site-packages/qds_sdk/commands.py", line 245, in get_results
    skip_data_avail_check=isinstance(self, PrestoCommand))
  File "/Users/amelio/anaconda/envs/py35/lib/python3.5/site-packages/qds_sdk/commands.py", line 1345, in _download_to_local
    _read_iteratively(one_path, fp, delim=delim)
  File "/Users/amelio/anaconda/envs/py35/lib/python3.5/site-packages/qds_sdk/commands.py", line 1236, in _read_iteratively
    fp.buffer.write(data.decode('utf-8').replace(chr(1), delim).encode('utf8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 8191: unexpected end of data
```

```
$ pip freeze | grep qds
qds-sdk==1.9.4
```

```
$ python --version
Python 3.5.2 :: Continuum Analytics, Inc.
```

**Comment by amelio-vazquez-reina** [comment]
And the above works without problem in `Python 2.7.12`

**Comment by mcarlsen** [comment]
Because of the 8192 bytes read block size, a utf-8 character can possibly be cut in two, causing the block to be invalid utf-8.

Can be fixed by not decoding the block, but instead encode the delimiter and do the replace operation with bytes instead of str.

See commit above.

**Comment by amelio-vazquez-reina** [comment]
@mcarlsen did you try opening a PR?

**Comment by mcarlsen** [comment]
Sorry, never got that far. I have now started #197
